all:
  children:
    vyos_routers:
      hosts:
        vyospve1:
          ansible_host: 10.1.10.61
          ansible_user: vyos
          ansible_password: "{{ lookup('env', 'PM_PASS') }}"
          ansible_connection: network_cli
          ansible_network_os: vyos