- name: Extract Ontap Disk
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Run Commands Extract QCOW disk and attach them to the Proxmox VM
      community.general.proxmox_kvm:
        api_user: root@pam
        api_port: 8006
        api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
        api_host: 10.1.10.31
        name: spynal
        node: pve1
        state: absent


