- name: Extract Ontap Disk
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Run Commands Extract QCOW disk and attach them to the Proxmox VM
      community.general.proxmox_kvm:
        api_user: root@pam
        api_port: 8006
        api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
        api_host: 10.1.10.31
        name: spynal
        node: pve1
        state: absent



- steps
 "sudo tar -xvf vsim-netapp-DOT9.10.1-cm_nodar.ova"
 qm disk import 500 vsim-NetAppDOT-simulate-disk1.vmdk local-lvm -format qcow2
 qm disk import 500 vsim-NetAppDOT-simulate-disk2.vmdk local-lvm -format qcow2 
 qm disk import 500 vsim-NetAppDOT-simulate-disk3.vmdk local-lvm -format qcow2
 qm disk import 500 vsim-NetAppDOT-simulate-disk4.vmdk local-lvm -format qcow2