- name: Create VM via Proxmox API
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create new VM with minimal options
      community.general.proxmox_kvm:
        api_user: root@pam
        api_port: 8006
        api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
        api_host: 10.1.10.31
        name: spynal
        node: pve1
        state: absent


